apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pod
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: helloapi
          image: hello:rasp
          imagePullPolicy: Never
