apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pod
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: helloapi
          image: 192.168.0.155:32000/hello:rasp
          ports:
            - containerPort: 80
